UniversityRegistrar/Models/Course.cs
using System.Collections.Generic;

namespace UniversityRegistrar.Models
{
  public class Course
  {
    public Course()
    {
        this.Students = new HashSet<CourseStudent>();
    }

    public int CourseId { get; set; }
    public string CourseName { get; set; }
    public string CourseNumber { get; set; }
    public virtual ICollection<CourseStudent> Students { get; set; }
  }
}

UniversityRegistrar/Models/CourseStudent.cs
namespace UniversityRegistrar.Models
{
  public class CourseStudent
  {       
    public int CourseStudentId { get; set; }
    public int StudentId { get; set; }
    public int CourseId { get; set; }
    public Student Student { get; set; }
    public Course Course { get; set; }
  }
}

UniversityRegistrar/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace UniversityRegistrar.Models
{
  public class UniversityRegistrarContextFactory : IDesignTimeDbContextFactory<UniversityRegistrarContext>
  {

    UniversityRegistrarContext IDesignTimeDbContextFactory<UniversityRegistrarContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<UniversityRegistrarContext>();
      var connectionString = configuration.GetConnectionString("DefaultConnection");

      builder.UseMySql(connectionString);

      return new UniversityRegistrarContext(builder.Options);
    }
  }
}

UniversityRegistrar/Models/Student.cs
using System.Collections.Generic;

namespace UniversityRegistrar.Models
{
  public class Student
  {
    public Student()
    {
      this.Courses = new HashSet<CourseStudent>();
    }

    public int StudentId { get; set; }
    public string StudentName { get; set; }
    public string EnrollmentDate { get; set; }

    public ICollection<CourseStudent> Courses { get; }
  }
}

UniversityRegistrar/Models/UniversityRegistrarContext.cs
using Microsoft.EntityFrameworkCore;

namespace UniversityRegistrar.Models
{
  public class UniversityRegistrarContext : DbContext
  {
    public virtual DbSet<Course> Courses { get; set; }
    public DbSet<Student> Students { get; set; }
    public DbSet<CourseStudent> CourseStudent { get; set; }

    public UniversityRegistrarContext(DbContextOptions options) : base(options) { }
  }
}

UniversityRegistrar/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using UniversityRegistrar.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace UniversityRegistrar.Controllers
{
  public class CoursesController : Controller
  {
    private readonly UniversityRegistrarContext _db;

    public CoursesController(UniversityRegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Course> model = _db.Courses.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Course course)
    {
      _db.Courses.Add(course);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Course thisCourse = _db.Courses
          .Include(course => course.Students)
          .ThenInclude(join => join.Student)
          .FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    public ActionResult Edit(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost]
    public ActionResult Edit(Course course)
    {
      _db.Entry(course).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Course thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      _db.Courses.Remove(thisCourse);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

UniversityRegistrar/Controllers/HomeController.cs
  
using Microsoft.AspNetCore.Mvc;

namespace UniversityRegistrar.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

UniversityRegistrar/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using UniversityRegistrar.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace UniversityRegistrar.Controllers
{
  public class StudentsController : Controller
  {
    private readonly UniversityRegistrarContext _db;

    public StudentsController(UniversityRegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Students.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "CourseName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Student student, int CourseId)
    {
      _db.Students.Add(student);
      if (CourseId != 0)
      {
        _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Student thisStudent = _db.Students
          .Include(student => student.Courses)
          .ThenInclude(join => join.Course)
          .FirstOrDefault(student => student.StudentId == id);
      return View(thisStudent);
    }

    public ActionResult Edit(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "CourseName");
      return View(thisStudent);
    }

    [HttpPost]
    public ActionResult Edit(Student student, int CourseId)
    {
      if (CourseId != 0)
      {
        _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId });
      }
      _db.Entry(student).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddCourse(int id)
    {
      Student thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "CourseName");
      return View(thisStudent);
    }

    [HttpPost]
    public ActionResult AddCourse(Student student, int CourseId)
    {
      if (CourseId != 0)
      {
        _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
      return View(thisStudent);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
      _db.Students.Remove(thisStudent);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteCourse(int joinId)
    {
      var joinEntry = _db.CourseStudent.FirstOrDefault(entry => entry.CourseStudentId == joinId);
      _db.CourseStudent.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

UniversityRegistrar/Views/Courses/Create.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Course

<h4>Add a new course</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.CourseName)
    @Html.TextBoxFor(model => model.CourseName)
    <input type="submit" value="Add new course" />
}
<p>@Html.ActionLink("Show all courses", "Index")</p>

UniversityRegistrar/Views/Courses/Delete.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Course

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.CourseName): @Html.DisplayFor(model => model.CourseName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to courses", "Index")

UniversityRegistrar/Views/Courses/Details.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Course;

<h2>Course Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.CourseName): @Html.DisplayFor(model => model.CourseName)</h3>

@if(@Model.Students.Count == 0)
{
  <p>This courses does not contain any students</p>
}
else
{
  <h4>Students the course contain:</h4>
  <ul>
  @foreach(var join in Model.Students)
  {
    <li>@join.Student.StudentName</li>
  }
  </ul>
}

<p>@Html.ActionLink("Back to Courses", "Index")</p>
<p>@Html.ActionLink("Edit Courses", "Edit", new { id = Model.CourseId })</p>
<p>@Html.ActionLink("Delete Courses", "Delete", new { id = Model.CourseId })</p>

UniversityRegistrar/Views/Courses/Edit.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Course

<h2>Edit</h2>

<h4>Edit this course: @Html.DisplayFor(model => model.CourseName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.CourseId)

    @Html.LabelFor(model => model.CourseName)
    @Html.EditorFor(model => model.CourseName)

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to courses", "Index")</p>

UniversityRegistrar/Views/Courses/Index.cshtml
@{
  Layout = "_Layout";
}

@using UniversityRegistrar.Models;
@model List<UniversityRegistrar.Models.Course>;

<h1>Courses</h1>

@if (@Model.Count == 0)
{
  <h3>No courses have been added yet!</h3>
} 

@foreach (Course course in Model)
{
  <li>@Html.ActionLink($"{course.CourseName}", "Details", new { id = course.CourseId })</li>
}

<p>@Html.ActionLink("Add new course", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>

UniversityRegistrar/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<br>

<button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">@Html.ActionLink("See all courses", "Index", "Courses")</button>
<button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">@Html.ActionLink("See all students", "Index", "Students")</button>

UniversityRegistrar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>University Registrar</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
  <div class="demo-layout-transparent mdl-layout mdl-js-layout">
  <header class="mdl-layout__header mdl-layout__header--transparent">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title">Registrar</span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation -->
      <nav class="mdl-navigation">
        <a class="mdl-navigation__link" href="/Students">Students</a>
        <a class="mdl-navigation__link" href="/Courses">Courses</a>
      </nav>
    </div>
  </header>
  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title">Title</span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link" href="/Students">Students</a>
      <a class="mdl-navigation__link" href="/Courses">Courses</a>
    </nav>
  </div>
  <main class="mdl-layout__content">
  </main>
</div>
    @RenderBody()
  </body>
</html>

UniversityRegistrar/Views/Students/AddCourse.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Student

<h2>Add a student</h2>

<h4>Add a course to this student: @Html.DisplayFor(model => model.StudentName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.StudentId)

    @Html.Label("Select course")
    @Html.DropDownList("CourseId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Students", "Index")</p>

UniversityRegistrar/Views/Students/Create.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Student

<h4>Add a new student</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.StudentName, new { @class="mdl-textfield__label" })
    @Html.TextBoxFor(model => model.StudentName, new { @class="mdl-textfield__input", @required="true"  })

    @Html.LabelFor(model => model.EnrollmentDate)
    @Html.EditorFor(model => model.EnrollmentDate)

    @Html.Label("Select course")
    @Html.DropDownList("CourseId")

    <input type="submit" value="Add new Student" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all Students", "Index")</p>

UniversityRegistrar/Views/Students/Delete.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Student

<h2>Are you sure you want to delete this student?</h2>

@Html.DisplayNameFor(model => model.StudentName): @Html.DisplayFor(model => model.StudentName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Students", "Index")

UniversityRegistrar/Views/Students/Details.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Student

<h2>Student Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.StudentName): @Html.DisplayFor(model => model.StudentName)</h3>

@if(@Model.Courses.Count == 0)
{
  <p>This Student does not belong to any Courses</p>
}
else
{
  <h4>Enrollment Date: @Html.DisplayFor(model => model.EnrollmentDate)</h4>
  <h4>Courses the Student belongs to:</h4>
  <ul>
  @foreach(var join in Model.Courses)
  {
    <li>@join.Course.CourseName</li>
    @using (Html.BeginForm("DeleteCourse", "Students"))
    {
      @Html.Hidden("joinId", @join.CourseStudentId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}

<p>@Html.ActionLink("Back to Students", "Index")</p>
<p>@Html.ActionLink("Edit Student", "Edit", new { id = Model.StudentId })</p>
<p>@Html.ActionLink("Add a Course", "AddCourse", new { id = Model.StudentId })</p>
<p>@Html.ActionLink("Delete Student", "Delete", new { id = Model.StudentId })</p>

UniversityRegistrar/Views/Students/Edit.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Student

<h2>Edit</h2>

<h4>Edit this task: @Html.DisplayFor(model => model.StudentName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.StudentId)

    @Html.LabelFor(model => model.EnrollmentDate)
    @Html.EditorFor(model => model.EnrollmentDate)

    @Html.Label("Select course")
    @Html.DropDownList("CourseId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Students", "Index")</p>

UniversityRegistrar/Views/Students/Index.cshtml
@{
  Layout = "_Layout";
}

@using UniversityRegistrar.Models;
@model List<UniversityRegistrar.Models.Student>;

<h1>Students</h1>

@if (@Model.Count == 0)
{
  <h3>No Students have been added yet!</h3>
} 

@foreach (Student student in Model)
{
  <li>@Html.ActionLink($"{student.StudentName}", "Details", new { id = student.StudentId })</li>
}

<p>@Html.ActionLink("Add new student", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>